---
- name: Deploy Python package to a remote server
  hosts: sshserver
  vars:
    local_package_path: "."
    remote_package_path: "/pizdec"
    package_name: "pizdec"

  tasks:
    - name: Archive the Python package
      ansible.builtin.command: tar cvfz {{ package_name }}.tar.gz -C {{ local_package_path }} {{ package_name }}
      delegate_to: localhost
      run_once: true

    - name: Copy the package to the remote server
      ansible.builtin.copy:
        src: "{{ local_package_path }}/{{ package_name }}.tar.gz"
        dest: "{{ remote_package_path }}/{{ package_name }}.tar.gz"

    - name: Extract the package on the remote server
      ansible.builtin.command: tar xvfz {{ remote_package_path }}/{{ package_name }}.tar.gz -C {{ remote_package_path }}

    - name: Install the package using pip
      ansible.builtin.command: pip install {{ remote_package_path }}/{{ package_name }}
